version: '3.8'

services:
  msb-product-sv:
    image: 13angs/msb-product-sv:latest
    build: 
      context: ../../../product-sv
      dockerfile: Dockerfile
    container_name: msb-product-sv

    ports:
      - "5005:5000"

    networks:
      - msb-network

networks:
  msb-network:
    external: true
    name: msb-network
