# consumer_name=consumer2 docker compose -p consumer2 up
version: '3.8'

services:
  msb-order-sv:
    image: 13angs/msb-order-sv:latest
    build: 
      context: ../../../order-sv
      dockerfile: Dockerfile
    container_name: msb-order-sv-${consumer_name}

    networks:
      - msb-network

networks:
  msb-network:
    external: true
    name: msb-network
